if((WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Linux") AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(golden_xdma_kit "${RTFW_DATA_DIR}/examples/golden_xdma")
    file(GLOB golden_xdma_sources LIST_DIRECTORIES FALSE RELATIVE "${golden_xdma_kit}" "${golden_xdma_kit}/*")
    list(SORT golden_xdma_sources)
    if(NOT "${golden_xdma_sources}" STREQUAL "CMakeLists.txt;README.md;artifacts.py;codec.hpp;io.hpp;main.cpp;oracle.hpp;owner.hpp;provenance.json;provenance.py;replay.hpp;run.py;runner.hpp;session.hpp;simulated_driver.hpp;state.py;telemetry.hpp")
        message(FATAL_ERROR "Golden XDMA source inventory differs from contract")
    endif()
    if(NOT EXISTS "${RTFW_DATA_DIR}/golden_xdma.md")
        message(FATAL_ERROR "Golden XDMA guide is missing")
    endif()
    add_subdirectory("${golden_xdma_kit}" golden-xdma)
endif()
