execute_process(COMMAND "${HELLO_EXECUTABLE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20)
string(REPLACE "\r\n" "\n" error "${error}")
if(NOT "${result}" STREQUAL "1" OR NOT "${output}" STREQUAL "")
    message(FATAL_ERROR "hello ${HELLO_FAILURE}: expected exit1 and no success output; ${result}; ${output}; ${error}")
endif()
if(HELLO_FAILURE STREQUAL "capacity")
    if(NOT "${error}" STREQUAL "register consume failed (-4): configured capacity exceeded\n")
        message(FATAL_ERROR "Unexpected capacity diagnostic: ${error}")
    endif()
elseif(HELLO_FAILURE STREQUAL "step")
    if(NOT "${error}" MATCHES "^step failed \\(-5\\): [^\n]+\nchecked stop reached\n$")
        message(FATAL_ERROR "Step error did not reach checked stop cleanly: ${error}")
    endif()
else()
    message(FATAL_ERROR "Unknown hello negative control")
endif()
