// Generated by tools/generate_golden_config.py; do not edit.
#pragma once
#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
namespace golden::fixed {
inline constexpr std::size_t capacity = 256;
inline constexpr std::size_t axes = 3;
inline constexpr std::size_t default_count = 16;
inline constexpr std::size_t default_ticks = 24;
inline constexpr std::size_t maximum_ticks = 1024;
inline constexpr std::size_t tick_ns = 10000000;
inline constexpr std::size_t supercycle_ticks = 6;
inline constexpr std::size_t queue_slots = 1024;
inline constexpr std::size_t task_slots = 1024;
inline constexpr std::size_t scratch_bytes = 64;
inline constexpr std::size_t runtime_budget = 134217728;
inline constexpr std::size_t sample_budget = 33554432;
inline constexpr std::size_t checkpoint_bytes = 4194304;
inline constexpr std::size_t artifact_bytes = 16777216;
inline constexpr std::size_t action_capacity = 16384;
inline constexpr std::string_view contract_sha256 = "9c93b5d5970caa5dc4570a4d0c43c9ca21ab7aa5a7211c02ce946cf8ffa62771";
inline constexpr std::string_view scenario_id = "rtfw.golden.vehicle.v1";
inline constexpr std::array<std::size_t, 5> periods{1, 2, 3, 3, 6};
inline constexpr std::array<std::uint64_t, 5> budgets{3000000, 1000000, 1000000, 1000000, 1000000};
inline constexpr std::array<std::size_t, 8> phase_rates{0, 0, 0, 1, 2, 3, 4, 4};
inline constexpr std::array<std::size_t, 5> channel_producers{2, 3, 4, 5, 2};
inline constexpr std::array<std::size_t, 5> channel_consumers{3, 4, 5, 0, 6};
inline constexpr std::array<std::size_t, 5> channel_elements{6, 6, 3, 3, 6};
inline constexpr std::array<std::size_t, 5> channel_age{2, 3, 3, 3, 6};
inline constexpr std::array<std::string_view, 8> phase_names{"input", "physics", "stage", "sensor", "controller", "actuator", "aggregate", "telemetry"};
inline constexpr std::array<std::string_view, 5> rate_names{"plant", "sensor", "controller", "actuator", "observe"};
inline constexpr std::array<std::string_view, 5> channel_names{"plant_sensor", "sensor_controller", "controller_actuator", "actuator_input", "plant_aggregate"};
} // namespace golden::fixed
