#!/usr/bin/env python3
"""Validate offline SDK links, fragments and exact shipped/generated bytes."""
import argparse
from html.parser import HTMLParser
import posixpath
from pathlib import Path
import re
from urllib.parse import unquote, urlsplit

import generate_sdk_docs as gen


class HtmlLinks(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links, self.anchors = [], set()

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if 'id' in attrs:
            if attrs['id'] in self.anchors:
                raise ValueError('duplicate HTML anchor')
            self.anchors.add(attrs['id'])
        for name in ('href', 'src'):
            if name in attrs:
                self.links.append(attrs[name])


def markdown_links(text):
    links, anchors, seen = [], set(), {}
    fenced = False
    for line in text.splitlines():
        if line.lstrip().startswith('```'):
            fenced = not fenced
            continue
        if fenced:
            continue
        links.extend(m[2].strip('<>') for m in gen.LINK.finditer(line))
        match = gen.REFERENCE.match(line)
        if match:
            links.append(match[2].strip('<>'))
        heading = re.match(r'^#{1,6}\s+(.+?)(?:\s+#+)?$', line)
        if heading:
            slug = re.sub(r'<[^>]+>', '', heading[1]).lower()
            slug = re.sub(r'[^\w\- ]', '', slug).replace(' ', '-')
            number = seen.get(slug, 0)
            seen[slug] = number + 1
            anchors.add(slug + ('-' + str(number) if number else ''))
    anchors.update(re.findall(r'(?:id|name)=["\']([^"\']+)["\']', text))
    return links, anchors


def check_links(files):
    parsed = {}
    for name, raw in files.items():
        if name.endswith('.html'):
            parser = HtmlLinks()
            parser.feed(raw.decode())
            parsed[name] = parser.links, parser.anchors
        elif name.endswith('.md'):
            parsed[name] = markdown_links(raw.decode())
    for name, (links, _) in parsed.items():
        # Earlier source kits include repository-oriented comments; validate the
        # newly shipped manual, whose links are explicitly rewritten for offline use.
        if not name.startswith('manual/'):
            continue
        for link in links:
            url = urlsplit(link)
            if url.scheme or url.netloc:
                if url.scheme not in ('https', 'http', 'mailto'):
                    raise ValueError(f'unsupported link scheme: {name}: {link}')
                continue
            target = posixpath.normpath(posixpath.join(posixpath.dirname(name), unquote(url.path))) if url.path else name
            if target.startswith('../') or target.startswith('/') or target not in files:
                raise ValueError(f'broken offline link: {name}: {link}')
            fragment = unquote(url.fragment)
            if fragment:
                if target in parsed and fragment not in parsed[target][1]:
                    raise ValueError(f'broken offline fragment: {name}: {link}')
                if target not in parsed:
                    match = re.fullmatch(r'L(\d+)(?:-L(\d+))?', fragment)
                    if not match or not 1 <= int(match[1]) <= len(files[target].splitlines()):
                        raise ValueError(f'invalid source fragment: {name}: {link}')


def verify(root=gen.ROOT, data_root=None):
    outputs = gen.render(root)
    gen.verify_outputs(root / gen.GENERATED, outputs)
    sources = gen.shipped_files(root, gen.inventory(root))
    expected = {name: path.read_bytes() for name, path in sources.items()}
    expected.update({'manual/' + name: text.encode() for name, text in outputs.items()})
    if data_root is not None:
        actual_manual = {p.relative_to(data_root / 'manual').as_posix() for p in (data_root / 'manual').rglob('*') if p.is_file()}
        if actual_manual != set(outputs):
            raise ValueError('installed manual inventory differs')
        actual_recipes = {p.relative_to(data_root).as_posix() for p in (data_root / 'examples/recipes').rglob('*') if p.is_file()}
        if actual_recipes != set(gen.recipe_files(root, gen.inventory(root))):
            raise ValueError('installed recipe inventory differs')
        for name, content in expected.items():
            path = data_root / name
            if not path.is_file() or path.read_bytes() != content:
                raise ValueError('installed documentation/source bytes differ: ' + name)
        files = {name: (data_root / name).read_bytes() for name in expected}
    else:
        files = expected
    check_links(files)
    print(f'PASS: SDK manual/API/source inventory and local fragments ({len(files)} files)')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data-root', type=Path)
    args = parser.parse_args()
    verify(data_root=args.data_root)


if __name__ == '__main__':
    main()
