#!/usr/bin/env python3
"""Bind compiled golden constants to the immutable reviewed M26-01 contract."""
import argparse
import json
from pathlib import Path
import check_golden_contract as contract

ROOT = Path(__file__).resolve().parents[1]

def render():
    d = contract.read(); contract.validate(d)
    s = d['state']; c = d['clock']; e = d['execution']
    out = ['// Generated by tools/generate_golden_config.py; do not edit.', '#pragma once', '#include <array>', '#include <cstddef>', '#include <cstdint>', '#include <string_view>', 'namespace golden::fixed {']
    for name,value in [('capacity',s['capacity']),('axes',s['axes']),('default_count',s['default_entities']),('default_ticks',c['default_ticks']),('maximum_ticks',c['maximum_ticks']),('tick_ns',c['base_tick_ns']),('supercycle_ticks',c['supercycle_ticks']),('queue_slots',e['queue_slots']),('task_slots',e['task_slots']),('scratch_bytes',e['task_scratch_bytes']),('runtime_budget',e['runtime_budget_bytes']),('sample_budget',e['sample_budget_bytes']),('checkpoint_bytes',d['controls']['checkpoint_bytes']),('artifact_bytes',d['controls']['artifact_bytes']),('action_capacity',d['telemetry']['capacity_each'])]:
        out.append(f'inline constexpr std::size_t {name} = {value};')
    out += [f'inline constexpr std::string_view contract_sha256 = "{contract.digest(d)}";', f'inline constexpr std::string_view scenario_id = "{d["scenario_id"]}";']
    for name,values,typ in [('periods',[r['period_ticks'] for r in d['rates']],'std::size_t'),('budgets',[r['budget_ns'] for r in d['rates']],'std::uint64_t'),('phase_rates',[[r['id'] for r in d['rates']].index(p['rate']) for p in d['phases']],'std::size_t'),('channel_producers',[[p['id'] for p in d['phases']].index(c['producer']) for c in d['channels']],'std::size_t'),('channel_consumers',[[p['id'] for p in d['phases']].index(c['consumer']) for c in d['channels']],'std::size_t'),('channel_elements',[c['elements_per_entity'] for c in d['channels']],'std::size_t'),('channel_age',[c['max_age_ticks'] for c in d['channels']],'std::size_t')]:
        out.append(f'inline constexpr std::array<{typ}, {len(values)}> {name}{{{", ".join(map(str,values))}}};')
    for name,rows in [('phase_names',d['phases']),('rate_names',d['rates']),('channel_names',d['channels'])]:
        out.append(f'inline constexpr std::array<std::string_view, {len(rows)}> {name}{{'+', '.join(json.dumps(r['id']) for r in rows)+'};')
    return '\n'.join(out+['} // namespace golden::fixed',''])

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    p=ROOT/'samples/golden_system/fixed.hpp';text=render()
    if args.check:
        if not p.is_file() or p.read_text(encoding='utf-8') != text: parser.exit(1,'stale golden constants; regenerate explicitly\n')
    else:p.write_text(text,encoding='utf-8')
    print('PASS: compiled golden constants match frozen contract')
if __name__=='__main__':main()
