if(RTFW_TEST_BENCHMARK AND (WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Linux") AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(golden_showcase_kit "${RTFW_DATA_DIR}/examples/golden_showcase")
    file(GLOB golden_showcase_sources LIST_DIRECTORIES FALSE RELATIVE "${golden_showcase_kit}" "${golden_showcase_kit}/*")
    list(SORT golden_showcase_sources)
    if(NOT "${golden_showcase_sources}" STREQUAL "CMakeLists.txt;README.md;artifacts.py;experiment_main.cpp;experiments.cpp;experiments.hpp;main.cpp;probes.hpp;provenance.json;provenance.py;provider.cpp;provider.hpp;replay.hpp;replay_gate.hpp;report.py;run.py;session.hpp;state.py;telemetry_loss.cpp;test.py;variants.cpp;variants.hpp")
        message(FATAL_ERROR "Golden showcase source inventory differs from contract")
    endif()
    if(NOT EXISTS "${RTFW_DATA_DIR}/golden_showcase.md")
        message(FATAL_ERROR "Golden showcase guide is missing")
    endif()
    add_subdirectory("${golden_showcase_kit}" golden-showcase)
endif()
